"""The judgment layer, without reaching the network.

The property under test throughout is containment: whatever the model answers,
the operations that come out of this layer are operations the domain already
built and already blessed. The model chooses among them and explains them; it
cannot add to them.
"""

from __future__ import annotations

from datetime import timedelta

import pytest

from fantasy.agent.advisor import Advisor, AdvisorError, system_prompt
from fantasy.agent.briefing import Candidate, millions, render
from fantasy.agent.schemas import Discard, Judgment, Pick
from fantasy.agent.selection import resolve
from fantasy.domain.intents import Intent, IntentKind
from fantasy.domain.models import Matchday, SquadRole

from .conftest import NOW, make_policy


def candidate(key_player: str = "99", amount: int = 20_000_000, **extra: object) -> Candidate:
    intent = Intent(
        kind=IntentKind.PAY_CLAUSE,
        execute_at=NOW,
        anchor=NOW + timedelta(days=2),
        player_id=key_player,
        player_name=f"Player {key_player}",
        amount=amount,
        rationale="generated by the planner",
    )
    return Candidate.model_validate({"intent": intent, "role": SquadRole.KEY, **extra})


class TestSelectionIsContained:
    def test_a_pick_resolves_to_the_planners_own_intent(self):
        item = candidate()
        judgment = Judgment(
            worth_saying=True,
            message="Ficha a este",
            picks=(Pick(key=item.key, reasoning="titular y subiendo"),),
        )
        selection = resolve(judgment, [item])

        assert len(selection.intents) == 1
        chosen = selection.intents[0]
        assert chosen.player_id == item.intent.player_id
        assert chosen.amount == item.intent.amount
        assert chosen.rationale == "titular y subiendo"

    def test_an_invented_key_is_dropped_and_reported(self):
        """The containment property: a hallucinated pick buys nothing."""
        judgment = Judgment(
            worth_saying=True,
            picks=(Pick(key="no-such-candidate", reasoning="confía en mí"),),
        )
        selection = resolve(judgment, [candidate()])

        assert selection.is_empty
        assert selection.unknown_keys == ("no-such-candidate",)

    def test_the_model_cannot_change_the_price(self):
        """Only the rationale travels back; every number stays the planner's."""
        item = candidate(amount=20_000_000)
        judgment = Judgment(
            worth_saying=True,
            picks=(Pick(key=item.key, reasoning="vale 90 millones, cómpralo"),),
        )
        assert resolve(judgment, [item]).intents[0].amount == 20_000_000

    def test_picks_come_back_in_priority_order(self):
        first, second = candidate("1"), candidate("2")
        judgment = Judgment(
            worth_saying=True,
            picks=(
                Pick(key=second.key, priority=9, reasoning="puede esperar"),
                Pick(key=first.key, priority=1, reasoning="urgente"),
            ),
        )
        order = [i.player_id for i in resolve(judgment, [first, second]).intents]
        assert order == ["1", "2"]

    def test_silence_resolves_to_nothing(self):
        assert resolve(Judgment(worth_saying=False), [candidate()]).is_empty


class TestSilenceIsFirstClass:
    def test_a_judgment_with_nothing_to_say_is_silent(self):
        assert Judgment(worth_saying=False).is_silent

    def test_picks_without_a_message_are_not_silence(self):
        item = candidate()
        judgment = Judgment(worth_saying=False, picks=(Pick(key=item.key, reasoning="x"),))
        assert not judgment.is_silent


class TestBriefing:
    def test_warns_loudly_when_the_squad_cannot_score(self, league):
        broke = league.model_copy(
            update={
                "teams": tuple(
                    t.model_copy(update={"can_punctuate": False}) if t.id == "mine" else t
                    for t in league.teams
                ),
            }
        )
        text = render(broke, make_policy(), [], now=NOW)
        assert "NO puntúa" in text

    def test_tells_the_model_which_features_this_league_lacks(self, league):
        text = render(league, make_policy(), [], now=NOW)
        assert "capitán" in text

    def test_includes_the_deadline_when_there_is_a_matchday(self, league):
        kickoff = NOW + timedelta(days=1)
        with_matchday = league.model_copy(update={"matchday": Matchday(number=5, opens_at=kickoff)})
        text = render(with_matchday, make_policy(), [], now=NOW)
        assert "Jornada 5" in text

    def test_says_so_plainly_when_there_are_no_candidates(self, league):
        assert "Ninguno hoy" in render(league, make_policy(), [], now=NOW)

    def test_a_candidate_is_rendered_under_its_key(self, league):
        item = candidate()
        text = render(league, make_policy(), [item], now=NOW)
        assert item.key in text
        assert "clave" in text

    def test_already_communicated_items_are_flagged_as_do_not_repeat(self, league):
        text = render(league, make_policy(), [], now=NOW, already_said=["abc123"])
        assert "NO lo repitas" in text
        assert "abc123" in text

    def test_amounts_use_spanish_conventions(self):
        assert millions(12_869_602) == "12,87 M"


class TestAdvisorFailsClosed:
    def test_a_transport_failure_raises_rather_than_inventing(self):
        class Exploding:
            class messages:  # noqa: N801
                @staticmethod
                def parse(**_: object) -> object:
                    raise RuntimeError("connection reset")

        with pytest.raises(AdvisorError):
            Advisor(Exploding()).judge("briefing")  # type: ignore[arg-type]

    def test_an_answer_without_a_judgment_raises(self):
        class Empty:
            class messages:  # noqa: N801
                @staticmethod
                def parse(**_: object) -> object:
                    return type("R", (), {"content": [], "stop_reason": "end_turn"})()

        with pytest.raises(AdvisorError):
            Advisor(Empty()).judge("briefing")  # type: ignore[arg-type]

    def test_a_refusal_raises(self):
        class Refusing:
            class messages:  # noqa: N801
                @staticmethod
                def parse(**_: object) -> object:
                    return type("R", (), {"content": [], "stop_reason": "refusal"})()

        with pytest.raises(AdvisorError):
            Advisor(Refusing()).judge("briefing")  # type: ignore[arg-type]


class TestSystemPrompt:
    """The prompt is a versioned artefact; these pin its load-bearing rules."""

    def test_it_loads(self):
        assert len(system_prompt()) > 500

    def test_it_makes_silence_the_default(self):
        assert "worth_saying: false" in system_prompt()

    def test_it_forbids_repeating_what_was_already_said(self):
        assert "Ya comunicado" in system_prompt()

    def test_it_warns_that_season_averages_mislead(self):
        assert "media de la temporada miente" in system_prompt()


def test_discard_records_a_reason():
    assert Discard(key="k", reason="suplente").reason == "suplente"
